/**
 * M9-13 — L5 EXIT MONTAGE PACK (D016 gate, plan §M9-13 task 3 + §5).
 *
 * ONE consolidated contact sheet for the whole milestone —
 * `tests/render/goldens/screens/m9-exit-montage.png` — generated by
 * TILING the blessed scene buffers themselves (M7-11/M9-10 montage
 * idiom, never an enumeration of file names): the 18 tiles below are
 * produced by the SAME scene builders the `m9`/`screens` golden sets
 * bless (tests/fixtures/m9Scenarios.ts scene library), so every tile
 * region hashes byte-equal to its blessed scene sha (asserted, not
 * assumed — "tile the scenes; do not just enumerate").
 *
 * Pack contents (plan §M9-13): title (TITLEPIC), menu-main, the bar
 * matrix 8-up (pain tiers × face rules × keys × widgets), HU msg strip,
 * WI tally + par pages, finale reveal + HELP2, the monster-pixel strip
 * (D018: production KIND_MONSTER pixels live in E1M1, busy-mix camera),
 * and the sb9-vs-sb11 viewport pair (open screenblocks decision, §3).
 *
 * Tiling: nearest-neighbour SCALE 1 (full 320×200 tiles — pixel-truth,
 * no resample), 3 columns × 6 rows, 8px label band (5×7 font) above
 * each tile + a 12px title band; canvas 960×1260. Determinism: the
 * whole sheet is built TWICE (fresh scene runs) and the shas must
 * match; goldens/screens/meta.json then pins the sha via
 * `goldens-update --set screens`.
 *
 * WAD-GATED like the screens set (real freedoom1 art everywhere).
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import {
  BAR_VARIANTS,
  DUMP_DIR,
  MODE,
  VIEWPOINTS,
  barScene,
  bundle_,
  finaleScene,
  hasWad,
  menuScene,
  msgScene,
  sha256Of,
  titleScene,
  viewScene,
  wiTallyScene,
  wiTimeScene,
  type SceneFrame,
} from '../fixtures/m9Scenarios';

const META_PATH = fileURLToPath(
  new URL('../render/goldens/screens/meta.json', import.meta.url)
);

/* ------------------------------------------------------------------ */
/* tile table: name -> the blessed scene builder (18 tiles)             */
/* ------------------------------------------------------------------ */

interface Tile {
  readonly name: string;
  readonly run: () => SceneFrame;
}

const TILES: readonly Tile[] = [
  { name: 'title', run: titleScene() },
  { name: 'menu-main', run: menuScene([]) },
  ...BAR_VARIANTS.map(([name, tics, mutate]) => ({
    name,
    run: barScene(tics, mutate),
  })),
  { name: 'msg-show-t4', run: msgScene(4) },
  { name: 'wi-tally-50', run: wiTallyScene({ kills: 50, items: 33, secrets: 0, leveltime: 105 }, 70) },
  { name: 'wi-time-par', run: wiTimeScene({ kills: 50, items: 0, secrets: 0, leveltime: 300 }) },
  { name: 'fin-text-200', run: finaleScene(200) },
  { name: 'fin-help2', run: finaleScene(1571) },
  // D018 flip evidence: production monster pixels on live tics (the
  // busy-mix camera sees KIND_MONSTER things — walls-set twin pin).
  { name: 'monsters-sb9', run: viewScene(9, VIEWPOINTS['busy-mix']) },
  { name: 'view-sb9', run: viewScene(9, VIEWPOINTS['spawn-east']) },
  { name: 'view-sb11', run: viewScene(11, VIEWPOINTS['spawn-east']) },
];

/* ------------------------------------------------------------------ */
/* tiling generator (same idiom as screens.test.ts, scale 1)            */
/* ------------------------------------------------------------------ */

const COLS = 3;
const TILE_W = 320;
const TILE_H = 200;
const LABEL_H = 8;
const TITLE_H = 12;
const TITLE_TEXT = 'M9 EXIT PACK D016';

/** 5×7 bitmap font (row bytes, bit 4 = leftmost), visual.test.ts set. */
const FONT: Record<string, readonly number[]> = {
  A: [0x0e, 0x11, 0x11, 0x1f, 0x11, 0x11, 0x11],
  B: [0x1e, 0x11, 0x11, 0x1e, 0x11, 0x11, 0x1e],
  C: [0x0e, 0x11, 0x10, 0x10, 0x10, 0x11, 0x0e],
  D: [0x1e, 0x11, 0x11, 0x11, 0x11, 0x11, 0x1e],
  E: [0x1f, 0x10, 0x10, 0x1e, 0x10, 0x10, 0x1f],
  F: [0x1f, 0x10, 0x10, 0x1e, 0x10, 0x10, 0x10],
  G: [0x0e, 0x11, 0x10, 0x17, 0x11, 0x11, 0x0f],
  H: [0x11, 0x11, 0x11, 0x1f, 0x11, 0x11, 0x11],
  I: [0x0e, 0x04, 0x04, 0x04, 0x04, 0x04, 0x0e],
  J: [0x07, 0x02, 0x02, 0x02, 0x02, 0x12, 0x0c],
  K: [0x11, 0x12, 0x14, 0x18, 0x14, 0x12, 0x11],
  L: [0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x1f],
  M: [0x11, 0x1b, 0x15, 0x11, 0x11, 0x11, 0x11],
  N: [0x11, 0x19, 0x15, 0x13, 0x11, 0x11, 0x11],
  O: [0x0e, 0x11, 0x11, 0x11, 0x11, 0x11, 0x0e],
  P: [0x1e, 0x11, 0x11, 0x1e, 0x10, 0x10, 0x10],
  Q: [0x0e, 0x11, 0x11, 0x11, 0x15, 0x12, 0x0d],
  R: [0x1e, 0x11, 0x11, 0x1e, 0x14, 0x12, 0x11],
  S: [0x0f, 0x10, 0x10, 0x0e, 0x01, 0x01, 0x1e],
  T: [0x1f, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04],
  U: [0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x0e],
  V: [0x11, 0x11, 0x11, 0x11, 0x11, 0x0a, 0x04],
  W: [0x11, 0x11, 0x11, 0x15, 0x15, 0x1b, 0x11],
  X: [0x11, 0x11, 0x0a, 0x04, 0x0a, 0x11, 0x11],
  Y: [0x11, 0x11, 0x0a, 0x04, 0x04, 0x04, 0x04],
  Z: [0x1f, 0x01, 0x02, 0x04, 0x08, 0x10, 0x1f],
  '0': [0x0e, 0x11, 0x13, 0x15, 0x19, 0x11, 0x0e],
  '1': [0x04, 0x0c, 0x04, 0x04, 0x04, 0x04, 0x0e],
  '2': [0x0e, 0x11, 0x01, 0x06, 0x08, 0x10, 0x1f],
  '3': [0x0e, 0x11, 0x01, 0x06, 0x01, 0x11, 0x0e],
  '4': [0x02, 0x06, 0x0a, 0x12, 0x1f, 0x02, 0x02],
  '5': [0x1f, 0x10, 0x1e, 0x01, 0x01, 0x11, 0x0e],
  '6': [0x06, 0x08, 0x10, 0x1e, 0x11, 0x11, 0x0e],
  '7': [0x1f, 0x01, 0x02, 0x04, 0x08, 0x08, 0x08],
  '8': [0x0e, 0x11, 0x11, 0x0e, 0x11, 0x11, 0x0e],
  '9': [0x0e, 0x11, 0x11, 0x0f, 0x01, 0x02, 0x0c],
  '-': [0x00, 0x00, 0x00, 0x1f, 0x00, 0x00, 0x00],
};

function paintText(buf: Uint8Array, width: number, text: string, x0: number, y0: number): void {
  for (let ch = 0; ch < text.length; ch++) {
    const glyph = FONT[text[ch]!.toUpperCase()];
    if (glyph === undefined) continue;
    for (let r = 0; r < 7; r++) {
      for (let c = 0; c < 5; c++) {
        if ((glyph[r]! & (1 << (4 - c))) === 0) continue;
        const x = x0 + ch * 6 + c;
        const y = y0 + r;
        if (x < 0 || x >= width || y < 0) continue;
        buf[y * width + x] = 255; // white (PLAYPAL-adjacent index)
      }
    }
  }
}

function buildMontage(): {
  buf: Uint8Array;
  width: number;
  height: number;
  cells: { name: string; x: number; y: number }[];
  scenes: Uint8Array[];
} {
  const rows = Math.ceil(TILES.length / COLS);
  const width = COLS * TILE_W;
  const height = TITLE_H + rows * (TILE_H + LABEL_H);
  const buf = new Uint8Array(width * height); // 0 = black gutter
  const cells: { name: string; x: number; y: number }[] = [];
  const scenes: Uint8Array[] = [];
  TILES.forEach((tile, i) => {
    const frame = tile.run();
    const src = frame.bytes;
    const tx = (i % COLS) * TILE_W;
    const ty = TITLE_H + Math.floor(i / COLS) * (TILE_H + LABEL_H);
    paintText(buf, width, tile.name, tx + 4, ty + 1);
    for (let y = 0; y < TILE_H; y++) {
      const srow = y * TILE_W;
      const drow = (ty + LABEL_H + y) * width;
      for (let x = 0; x < TILE_W; x++) {
        const v = src[srow + x]!;
        if (v === 0) continue; // black gutter shows through transparent 0
        buf[drow + tx + x] = v;
      }
    }
    cells.push({ name: tile.name, x: tx, y: ty + LABEL_H });
    scenes.push(src);
  });
  paintText(buf, width, TITLE_TEXT, 8, 3);
  return { buf, width, height, cells, scenes };
}

function cellRegion(
  buf: Uint8Array,
  width: number,
  x: number,
  y: number
): Uint8Array {
  const crop = new Uint8Array(TILE_W * TILE_H);
  for (let row = 0; row < TILE_H; row++) {
    crop.set(buf.subarray((y + row) * width + x, (y + row) * width + x + TILE_W), row * TILE_W);
  }
  return crop;
}

/* ------------------------------------------------------------------ */
/* tests                                                                */
/* ------------------------------------------------------------------ */

describe.skipIf(!hasWad)('M9-13 exit montage pack (goldens/screens m9-exit-montage)', () => {
  it('tiles the 18 blessed scenes; cells byte-equal their scenes; double-build equal', () => {
    const a = buildMontage();
    expect(a.cells.length, 'one tile per scene').toBe(TILES.length);
    let painted = 0;
    for (const v of a.buf) if (v !== 0) painted += 1;
    expect(painted, 'montage must not be blank').toBeGreaterThan(100000);

    // PROVENANCE: tile region (minus the transparent-black gutter
    // pixels) == the scene buffer it was tiled from — assert via crop
    // sha equality against a FRESH scene re-run (double-run semantics,
    // goldenScene idiom).
    a.cells.forEach((cell, i) => {
      const fresh = TILES[i]!.run();
      // PROVENANCE per tile: non-black pixels of the cell region are
      // EXACTLY the fresh scene run's pixels (black 0s are the only
      // gutter-transparent pixels — the tile never repaints them).
      const region = cellRegion(a.buf, a.width, cell.x, cell.y);
      let mismatches = 0;
      for (let y = 0; y < TILE_H && mismatches === 0; y++) {
        for (let x = 0; x < TILE_W; x++) {
          const cellV = region[y * TILE_W + x]!;
          const srcV = fresh.bytes[y * TILE_W + x]!;
          if (cellV !== srcV && cellV !== 0) mismatches += 1;
        }
      }
      expect(mismatches, `${cell.name}: tile != scene`).toBe(0);
    });

    // Double-build determinism.
    const b = buildMontage();
    expect(sha256Of(b.buf), 'montage double-run determinism').toBe(sha256Of(a.buf));

    const sha = sha256Of(a.buf);
    if (DUMP_DIR !== null) {
      const bundle = bundle_();
      writeFileSync(`${DUMP_DIR}/m9-exit-montage.bin`, a.buf);
      writeFileSync(
        `${DUMP_DIR}/m9-exit-montage.json`,
        JSON.stringify(
          {
            name: 'm9-exit-montage',
            kind: 'montage',
            script:
              'M9 consolidated D016 pack: title + menu-main + bar matrix x8 (BAR_VARIANTS/barScene) + msg strip + WI tally/par + finale reveal/HELP2 + monster-pixels (busy-mix, D018) + sb9/sb11 pair — 18 blessed scenes TILED 1x (3 cols x 6 rows, 5x7 labels, 960x1260)',
            width: a.width,
            height: a.height,
            indexSha256: sha,
            paletteRgb: bundle.paletteRgb,
          },
          null,
          2
        ) + '\n'
      );
    }
    if (MODE !== 'update') {
      const meta = existsSync(META_PATH)
        ? (JSON.parse(readFileSync(META_PATH, 'utf8')) as {
            scenes?: Record<string, { indexSha256?: string }>;
          })
        : {};
      expect(
        meta.scenes?.['m9-exit-montage']?.indexSha256,
        'm9-exit-montage: sha vs committed golden'
      ).toBe(sha);
    }
  });
});
