// SPDX-License-Identifier: GPL-2.0-or-later
// scripts/license-audit.mjs — M12-07 GPL/license/credits audit
// (docs/design/M12-plan.md §M12-07). Re-runnable; wired into `npm run check`.
//
// Checks (all must pass):
//   1. LICENSE  — the GPL text is present and package.json declares it.
//   2. HEADERS  — every tracked .ts/.mjs carries the SPDX header line
//      `SPDX-License-Identifier: GPL-2.0-or-later` within its first 120 lines.
//      (docs/*.md are exempt by task scope; .refs/** are verbatim reference
//      text, not shipped source.)
//   3. BLOBS    — ZERO binary blobs tracked, with ONE carved-out exception:
//      blessed test goldens under tests/**/goldens/** (.png/.bin). These are
//      derived render/audio artifacts regenerated by `npm run goldens:update`
//      (bit-exact from Freedoom bytes fetched at RUNTIME — the assets
//      themselves are never committed), not content redistribution. `wads/`
//      must be gitignored AND contribute zero tracked files.
//   4. NAMES    — grep gate over string LITERALS in every tracked .ts/.mjs:
//      literals that look like DOOM lump names (uppercase, ≤9 chars) must
//      classify into the rule table below. The distinction we enforce is
//      PROTOCOL IDENTIFIER vs ASSET BYTES: naming a lump is required to read
//      a user-supplied WAD (the format's compatibility interface); copying its
//      bytes is what a GPL-clean port must never do — and check 3 + the
//      wads/ gitignore assert the bytes are never here. Every match must land
//      on an allowed rule with a documented classification; anything
//      unclassified is a FAIL (add a reasoned rule/entry to the table).
//      Run with --report to dump every match and its verdict.
//   5. CREDITS  — CREDITS.md is release-complete: Freedoom attribution
//      (BSD-3-Clause text), pinned release tag + sha256 values matching
//      scripts/freedoom/release.json, tooling credits, the GPL source-offer
//      statement, and the SPDX line.
//
// Exit code 0 = green, 1 = findings (printed per section).

import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname.replace(/\/$/, '');
const REPORT = process.argv.includes('--report');

const git = (...args) =>
  execFileSync('git', args, { cwd: ROOT, encoding: 'utf8' });
const tracked = git('ls-files').trim().split('\n');
const read = (rel) => readFileSync(join(ROOT, rel), 'utf8');

const failures = [];
const fail = (section, msg) => failures.push(`${section}: ${msg}`);

// ---------------------------------------------------------------- 1. LICENSE
{
  if (!existsSync(join(ROOT, 'LICENSE'))) fail('license', 'LICENSE missing');
  else {
    const lic = read('LICENSE');
    if (!/GNU GENERAL PUBLIC LICENSE/i.test(lic))
      fail('license', 'LICENSE is not the GNU GPL text');
    if (!/version 2 of the License|GNU GPL version 2/i.test(lic))
      fail('license', 'LICENSE does not state GPL version 2 terms');
  }
  const pkg = JSON.parse(read('package.json'));
  if (pkg.license !== 'GPL-2.0-or-later')
    fail('license', `package.json license is "${pkg.license}"`);
  if (!pkg.scripts?.check?.includes('license-audit'))
    fail('license', 'check chain does not run license-audit');
}

// --------------------------------------------------------------- 2. HEADERS
{
  const sources = tracked.filter((f) => /\.(ts|mjs)$/.test(f));
  const missing = [];
  for (const f of sources) {
    const head = read(f).split('\n', 120).join('\n');
    if (!/^.*SPDX-License-Identifier: GPL-2\.0-or-later.*$/m.test(head))
      missing.push(f);
  }
  if (missing.length)
    fail(
      'headers',
      `${missing.length} file(s) lack the SPDX header: ${missing.join(', ')}`
    );
  console.log(
    `HEADERS: ${sources.length - missing.length}/${sources.length} tracked .ts/.mjs carry the SPDX header (docs/*.md exempt per §M12-07)`
  );
}

// ----------------------------------------------------------------- 3. BLOBS
{
  // A golden artifact is allowed to be binary; nothing else may be.
  const GOLDEN = /^tests\/[\w\-/]*goldens\/[\w\-.\/]+\.(png|bin)$/;
  const isBinary = (buf) => buf.includes(0);
  const blobs = [];
  for (const f of tracked) {
    const fd = readFileSync(join(ROOT, f));
    const head = fd.subarray(0, 8192);
    if (isBinary(head) && !GOLDEN.test(f)) blobs.push(f);
  }
  if (blobs.length)
    fail('blobs', `tracked binary blobs outside the goldens carve-out: ${blobs.join(', ')}`);
  const gitignore = read('.gitignore');
  if (!/^\s*wads?\/?\s*$/m.test(gitignore))
    fail('blobs', '.gitignore does not ignore wads/');
  const wadTracked = tracked.filter((f) => /^wads?\//.test(f));
  if (wadTracked.length)
    fail('blobs', `tracked files under wads/: ${wadTracked.join(', ')}`);
  const goldens = tracked.filter((f) => GOLDEN.test(f) && isBinary(readFileSync(join(ROOT, f)).subarray(0, 8192)));
  console.log(
    `BLOBS: ${tracked.length} tracked files, ${goldens.length} binary (all blessed test goldens under tests/**/goldens/** — derived, regenerable, see header note); 0 under wads/; wads/ gitignored`
  );
}

// ---------------------------------------------------------------- 4. NAMES
//
// Rule table. Order matters: first match wins. `verdict: 'allow'` only;
// entries exist to DOCUMENT why a name-literal is a protocol/format
// identifier or a by-name content reference — never committed asset bytes.
const FORMAT_NAMES = [
  // WAD container / map-format structural names (docs/research/01-wad-container.md)
  'THINGS', 'LINEDEFS', 'SIDEDEFS', 'VERTEXES', 'NODES', 'SEGS', 'SSECTORS',
  'SECTORS', 'REJECT', 'BLOCKMAP', 'TEXTURE1', 'TEXTURE2', 'PNAMES', 'PLAYPAL',
  'COLORMAP', 'F_SKY1', 'F_START', 'F_END', 'S_START', 'S_END', 'P_START',
  'P_END', 'FLEVEL', 'GL_LEVEL', 'SLOPES', 'CEILINGS', 'FLATDEFS', 'DEHACKED',
  'IWAD', 'PWAD', 'WADVER', 'WMAPINFO', 'FALLGALS', 'MOBJtable', 'SOUNDinfo',
  'SPRITES', 'LIGHTS',
  // DOOMWAD.DOS engine-compat names (the iwad-finder protocol, docs/research/01)
  'DOOM', 'DOOM_1', 'DOOM2', 'PLUTONIA', 'TNT1', 'FREEDEM', 'ULTIMATE_DOOM',
  // sounds.c table identifiers referenced by the sfx code
  'S_sfx', 'S_npc', 'S_player', 'S_weapons',
  // PNG/vvideo chunk names (our own container format, docs/research/02)
  'IHDR', 'IDAT', 'IEND', 'PLTE', 'PNG', 'WADS', 'SIGNATURE',
  // C-source identifiers transcribed by the table extractors (not lump names)
  'NULL', 'NONE', 'NUMSTATES', 'NUMSFXS', 'NAME', 'ARRAY',
  // our savegame codec's own chunk tag (docs/research/11-persistence)
  'DBP1', 'DBPS', 'DBPD',
].map((n) => [n, 'format/protocol identifier required by the container, table, or engine-compat protocol; not an asset']);

// The SPRITES-table sprite names, read from the transcribed table itself.
const sprnames = [
  ...read('src/wad/info/sprnames.ts').matchAll(/'([A-Z0-9]{4})'/g),
].map((m) => m[1]);

const rules = [
  {
    id: 'fixture',
    test: (name, path) =>
      /^(tests|e2e)\//.test(path) || /\.test\.ts$/.test(path),
    classification: 'test-fixture',
    rationale:
      'test code fabricates lump bytes in-memory and uses names as dict keys; tests ship nothing',
  },
  {
    id: 'format',
    test: (name) => FORMAT_NAMES.some(([n]) => n === name),
    classification: 'format',
    rationale:
      'names the WAD/PNG/C formats and the engine-compat protocol REQUIRE verbatim (E1M1-style map names below, S_START/S_END range markers, structural lumps, DOOMWAD names) — identifiers, not assets',
  },
  {
    id: 'map-name',
    test: (name) => /^E[1-4]M[1-9]$/.test(name) || /^MAP\d\d$/.test(name),
    classification: 'format',
    rationale:
      'episode/map naming scheme of the shareware and DOOM 2 formats — protocol identifiers for map lookup (the map DATA is the user-supplied WAD)',
  },
  {
    id: 'music-ref',
    test: (name) => /^D_[A-Z0-9]{2,8}$/.test(name) || name === 'NEWLEVEL',
    classification: 'content-ref',
    rationale:
      'music-lump names (d_music ordering table); bytes fetched from the user-supplied WAD at runtime — Freedoom ships same-named lumps (docs/research/12-freedoom.md)',
  },
  {
    id: 'sfx-ref',
    test: (name) => /^DS[A-Z0-9]{0,8}$/.test(name),
    classification: 'content-ref',
    rationale:
      'DS_* names are the sfdseqtables/sfxinfo sound-lump table: protocol names referencing lumps fetched from Freedoom at runtime — the sound BYTES are never committed',
  },
  {
    id: 'sprite-ref',
    test: (name) =>
      sprnames.includes(name) ||
      (/^[A-Z]{4}[A-Z][0-9]([A-Z][0-9])?$/.test(name) &&
        sprnames.includes(name.slice(0, 4))),
    classification: 'content-ref',
    rationale:
      'sprite names from the transcribed SPRITES table (src/wad/info/sprnames.ts) and their frame/rotation forms — by-name references; patched sprite graphics come from the runtime WAD',
  },
  {
    id: 'menu-ref',
    test: (name) => /^M_[A-Z0-9]{2,8}$/.test(name),
    classification: 'content-ref',
    rationale:
      'menu graphic lump names transcribed from m_menu.c setup tables; graphics fetched from the runtime WAD',
  },
  {
    id: 'wi-hud-ref',
    test: (name) =>
      /^WI[A-Z0-9]{1,5}$/.test(name) ||
      /^WIP[A-Z]{1,3}\d?$/.test(name) ||
      /^ST[A-Z0-9]{1,7}$/.test(name) ||
      /^PD_[A-Z]{2,6}[A-Z0-9]?$/.test(name) ||
      /^FLOOR\d_\d$/.test(name) ||
      /^SKY\d$/.test(name) ||
      /^(TITLEPIC|INTERPIC|ENDPIC|CREDIT|HELP1|HELP2|HELP|GAMEOVER|VICTORY2|WIDE|POSTAGE|CELLNUM3|STARMS|BPAK|SHEL|STCFN\d\d\d)$/.test(name),
    classification: 'content-ref',
    rationale:
      'intermission/status-bar/menu GRAPHIC patch + finale/border FLAT and SKY names transcribed from wi_stuff.c / st_stuff.c / m_menu.c / d_englsh draw calls — by-name references into the runtime WAD',
  },
  {
    id: 'text-ref',
    test: (name) => /^GOT[A-Z]+$/.test(name) || name === 'GGSAVED' || /^GS_[A-Z]+$/.test(name),
    classification: 'derived-source',
    rationale:
      'strings transcribed from the id GPL source (d_englsh.h pickup messages, game-over texts) under PROMPT.md §2 provenance — text, not lump names',
  },
  {
    id: 'switchlist',
    test: (name, path) => path === 'src/wad/switchlist.ts',
    classification: 'content-ref',
    rationale:
      'switch/texture/flat names transcribed from the GPL source switch table (SW1./SW2. pairs) — by-name texture references resolved against the runtime WAD',
  },
  {
    id: 'episode-text',
    test: (name) => /^[FE]\dTEXT$/.test(name),
    classification: 'content-ref',
    rationale:
      'episode-ending TEXT lump names (finale background text) — by-name references into the runtime WAD',
  },
  {
    id: 'dev-label',
    test: (name) =>
      /^(FIRELIGHT|LIGHT1|LIGHT2|RAISE|OPEN|ADDRSHIFT|FONT|FIXMAP|FIXWALL\d|FIXFLAT\d|FLAT[AB]\d?|DOORFIX\d|E1M1THNG|NEWLEVEL)$/.test(name),
    classification: 'synthetic/label',
    rationale:
      'internal labels (special display names, door-action docs) or synthetic FIXMAP-style test-map fixtures invented by this project — not id assets',
  },
];

{
  const scanFiles = tracked.filter((f) => /\.(ts|mjs)$/.test(f));
  const LIT = /['"]([A-Z][A-Z0-9_]{1,8}|S_[a-z]{2,4})['"]/g;
  const verdicts = new Map(); // ruleId -> count
  const unknown = [];
  let total = 0;
  for (const f of scanFiles) {
    const lines = read(f).split('\n');
    lines.forEach((raw, i) => {
      const line = raw.trim();
      if (line.startsWith('//') || line.startsWith('*') || line.startsWith('/*'))
        return; // comments document; the gate is about CODE constants
      for (const m of line.matchAll(LIT)) {
        total++;
        const rule = rules.find((r) => r.test(m[1], f));
        if (rule) verdicts.set(rule.id, (verdicts.get(rule.id) ?? 0) + 1);
        else unknown.push(`${f}:${i + 1} '${m[1]}'`);
      }
    });
  }
  if (unknown.length)
    fail(
      'names',
      `${unknown.length} lump-name-like literal(s) unclassified (add a reasoned allowlist rule):\n  ${unknown.join('\n  ')}`
    );
  console.log(`NAMES: ${total} uppercase string literals scanned across ${scanFiles.length} files`);
  for (const r of rules) {
    const n = verdicts.get(r.id) ?? 0;
    console.log(`  [${String(n).padStart(5)}] ${r.id.padEnd(12)} (${r.classification}) — ${r.rationale}`);
  }
  if (REPORT) {
    // --report: dump every match with its verdict (audit evidence).
    for (const f of scanFiles)
      read(f)
        .split('\n')
        .forEach((raw, i) => {
          const line = raw.trim();
          if (/^(\/\/|\*|\/\*)/.test(line)) return;
          for (const m of line.matchAll(LIT)) {
            const rule = rules.find((r) => r.test(m[1], f));
            console.log(`  ${f}:${i + 1} '${m[1]}' -> ${rule?.id ?? 'UNKNOWN'}`);
          }
        });
  }
}

// -------------------------------------------------------------- 5. CREDITS
{
  if (!existsSync(join(ROOT, 'CREDITS.md'))) fail('credits', 'CREDITS.md missing');
  else {
    const c = read('CREDITS.md');
    const need = [
      [/\bFreedoom\b/, 'Freedoom attribution'],
      [/BSD[- ]3[- ]Clause/i, 'BSD-3-Clause license text'],
      [
        /Redistribution and use in source and binary forms/,
        'BSD-3 redistribution conditions',
      ],
      [/\[?[A-Fa-f0-9]{64}\]?/, 'a sha256 pin'],
      [/sha256/i, 'sha256 labeling'],
      [/scripts\/freedoom\/release\.json/, 'pinning pointer to release.json'],
      [/TypeScript/i, 'tooling credits'],
      [/github\.com\/freedoom\/freedoom\/releases\/tag\/v/, 'release-tag link'],
      [/source[- ]offer|Corresponding Source/i, 'GPL source-offer statement'],
      [/npm run build/, 'build instructions in the source offer'],
      [/GPL-2\.0-or-later/, 'SPDX identifier'],
      [/no id Software (asset|content)/i, 'no-id-assets statement'],
    ];
    for (const [re, what] of need)
      if (!re.test(c)) fail('credits', `CREDITS.md missing ${what}`);
    // sha pins must MATCH the machine-readable pin file, not drift from it.
    const rel = JSON.parse(read('scripts/freedoom/release.json'));
    for (const hex of [rel.zipSha256, ...rel.entries.map((e) => e.sha256)])
      if (hex && !c.includes(hex))
        fail('credits', `CREDITS.md does not carry the pinned sha256 ${hex}`);
    console.log(
      `CREDITS: Freedoom block + BSD-3 text + ${rel.entries.length + 1} sha256 pins (match scripts/freedoom/release.json) + tooling + source-offer present`
    );
  }
}

// ------------------------------------------------------------------ verdict
if (failures.length) {
  console.error(`\nLICENSE AUDIT FAILED (${failures.length}):`);
  for (const f of failures) console.error('  - ' + f);
  process.exit(1);
}
console.log('\nlicense-audit: PASS — GPL-2.0-or-later clean-room posture verified');
